---
to: components/routes/service-routes.js
---
const { validateRequest } = require('express-oas-validator');
const dynamicDebug = require('@infinitas/dynamic-debug');

const { ROLES } = require('@he-learning/service-he-common');

module.exports = () => {
  const start = async ({ app, auth, manifest = {} }) => {
    /**
     * GET /__/manifest
     * @summary This endpoint serves the manifest
     * @tags Service - Operations on system configuration
     * @return {object} 200 - Sucessful response
    */
    app.get('/__/manifest', (req, res) => res.json(manifest));

    /**
     * POST /debug
     * @summary Endpoint to dynamically enable / disable the `DEBUG` flag when
     *  running the app in the deployed services. With this, we can request
     *  messages generated by the `debug` function to appear in the service
     *  logs on demand.
     * @tags Service - Operations on system configuration
     * @param {DynamicDebugRequest} request.body.required - Desired debug
     *  flag state and namespace filters
     * @return {DynamicDebugResponse} 200 - Successful operation
     * @return {Common.ErrorMessage} 401 - Non authenticated user
     * @return {Common.ErrorMessage} 403 - Forbidden access to requested resource
     * @return {Common.ErrorMessage} 500 - Internal server error
     * @security JWT
     */
    app.use(dynamicDebug(app, '/debug', [
      auth.authenticate,
      auth.authorise('role')([ROLES.ADMIN]),
      validateRequest(),
    ]));

    return Promise.resolve();
  };

  return { start };
};
